### ISSUE TITLE
검색기능 갯수를 제한해야할 필요성

### ISSUE THREAD

**Issue by about-joo91** [about-joo91/Did_it_walk#32]
어제 저장한 db를 토대로 shoes 태그 검색기능을 써봤더니 5000장 전체를 화면에서 javascript로 없앴다가 나타냈다가 하니까 렉이걸리네요

그래서 100장 정도로 제한해서 보여준다던지 해야할 것 같습니다.

**Comment by about-joo91** [comment]
`                        {% for all_shoe in all_shoe_list %}
                        {% if forloop.counter < 100 %}
                        <div class="input_tag_title_list">
                            <div class="input_tag_title_list_obj" id="input_tag_title_list_obj_{{all_shoe.tag_title}}" onclick="take_tag_title('{{all_shoe.tag_title}}')">
                                {{all_shoe.tag_title}}
                            <hr>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}`

이렇게 loop.count 컨트롤도 가능하네요 ㅎㅎ

**Comment by khw7876** [comment]
아하 알겠습니다!! 30개정도로 제한 걸어서 해보겠습니다!!

**Comment by khw7876** [comment]
30개 제한해서 올렸습니다!
